/**
 * Credit system config — shared between client and server. Pure constants,
 * no Node APIs, so it is safe to import from React components.
 *
 * INDIEGEN meters generation in credits. On localhost we charge per
 * image-producing API call (the expensive ones); text/vision QA calls are
 * free. Marketing per-asset prices (sprite=10, full character=60, …) are a
 * P2 reconciliation once real economics are measured.
 */

/** Reown AppKit project id (wallet connect). Env override for prod. */
export const REOWN_PROJECT_ID =
  process.env.NEXT_PUBLIC_REOWN_PROJECT_ID || '761c6637f8efd83cff05e5f759b51e3f'

/** SPL Token-2022 program id (our token is a Token-2022 mint, 6 decimals). */
export const TOKEN_2022_PROGRAM_ID = 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb'

/**
 * $INDIEGEN token config. Driven by env so a single server command can flip
 * the whole app onto the real mint the moment it's launched — no code change.
 * Until NEXT_PUBLIC_TOKEN_MINT is set the app runs in test mode (dev faucet).
 *
 *   npm run set-token -- <MINT> <TREASURY> [network]
 */
export const TOKEN = {
  /** Token-2022 mint of $INDIEGEN. Empty until launched. */
  MINT: process.env.NEXT_PUBLIC_TOKEN_MINT || '',
  /** Token-2022 program (not legacy SPL-Token). */
  PROGRAM_ID: TOKEN_2022_PROGRAM_ID,
  /** 6 decimals. */
  DECIMALS: 6,
  /** Wallet that receives token payments for credits. */
  TREASURY: process.env.NEXT_PUBLIC_TOKEN_TREASURY || '',
  /** USD value of one whole token at launch (set via env). */
  USD_PRICE: Number(process.env.NEXT_PUBLIC_TOKEN_USD_PRICE || '0.001'),
  /** Credits granted per 1 whole token paid. */
  CREDITS_PER_TOKEN: 1,
  /** Network used for wallet + payments. */
  NETWORK: (process.env.NEXT_PUBLIC_SOLANA_NETWORK || 'solana-mainnet') as
    | 'solana-mainnet'
    | 'solana-devnet',
}

/** True once a real mint + treasury are configured (token is live). */
export function isTokenLive(): boolean {
  return Boolean(TOKEN.MINT && TOKEN.TREASURY)
}

/**
 * Pay in native SOL instead of the SPL token. Useful for demos / a simpler
 * payment rail (no burn — SOL just goes to the treasury). Set
 * NEXT_PUBLIC_PAY_IN_SOL=true to enable.
 */
export const PAY_IN_SOL = process.env.NEXT_PUBLIC_PAY_IN_SOL === 'true'

/** Wrapped-SOL mint — used to read the live SOL/USD price. */
export const WSOL_MINT = 'So11111111111111111111111111111111111111112'

/** Whether paid generation is active (either SOL mode or the SPL token). */
export function isPaymentLive(): boolean {
  return Boolean(TOKEN.TREASURY) && (PAY_IN_SOL || Boolean(TOKEN.MINT))
}

/**
 * Share of each generation payment that is BURNED (basis points; 5000 = 50%).
 * The remainder goes to the treasury. Tunable via env without a code change.
 */
export const BURN_BPS = Math.max(
  0,
  Math.min(10000, Number(process.env.NEXT_PUBLIC_BURN_BPS || '5000'))
)

/**
 * PRICING — every generation has a fixed price in USD. Balances are stored in
 * whole US cents (integer) so a prepaid balance never drifts with the token
 * price. You top up by sending $INDIEGEN (valued at the LIVE DexScreener price
 * at purchase time); each generation then costs its exact USD value.
 *
 * Tune these freely — they're retail prices (provider cost + margin).
 */
export const USD_COSTS = {
  /** Each image generated by /api/generate. (~$0.03 cost) */
  image: 0.05,
  /** Each outpaint step by /api/extend. */
  extend: 0.05,
  /** 3D model — representative flat; the 3D route overrides with estimate3DUsd. */
  model3d: 5,
  /** AI planning calls — scene brief, prop "art director" ideation. */
  brief: 0.01,
  /** AI vision QA passes — tile + sprite "art director" reviews. */
  review: 0.01,
} as const

export type CreditAction = keyof typeof USD_COSTS

/** Cents per dollar — the unit balances and costs are stored in. */
export const CENTS = 100
export const usdToCents = (usd: number) => Math.round(usd * CENTS)
export const centsToUsd = (cents: number) => cents / CENTS

/** Cost of an action in cents (integer). */
export function actionCostCents(action: CreditAction): number {
  return usdToCents(USD_COSTS[action])
}

/** Free trial granted to a fresh wallet, in cents ($0.20). */
export const SIGNUP_BONUS = usdToCents(0.2)

/** Dev faucet grant, in cents ($5). */
export const FAUCET_AMOUNT = usdToCents(5)

/**
 * 3D model pricing — charged in $INDIEGEN, scaled by prompt complexity.
 * A simple prompt lands near $2, a rich/rigged/multi-material one near $15.
 * (3D studio ships as a later update; this is the pricing it will use.)
 */
export const MODEL3D_USD = {
  MIN: Number(process.env.NEXT_PUBLIC_MODEL3D_USD_MIN || '2'),
  MAX: Number(process.env.NEXT_PUBLIC_MODEL3D_USD_MAX || '15'),
} as const

const COMPLEXITY_HINTS =
  /\b(rig|rigged|riggable|animat\w*|texture[ds]?|pbr|normal\s*map|detailed|intricate|ornate|multiple|several|scene|character|creature|armou?r|mechanical|robot|realistic|hi[- ]?poly|high[- ]?poly|sculpt\w*)\b/gi

/** Estimate the USD price of a 3D generation from its prompt ($2–$15). */
export function estimate3DUsd(prompt: string): number {
  const words = prompt.trim().split(/\s+/).filter(Boolean).length
  const hits = (prompt.match(COMPLEXITY_HINTS) || []).length
  const score = Math.min(1, (words / 45) * 0.6 + (hits / 6) * 0.4)
  const usd = MODEL3D_USD.MIN + score * (MODEL3D_USD.MAX - MODEL3D_USD.MIN)
  return Math.round(usd * 100) / 100
}

/** Convert a USD price to a token amount at a given live token price ($/token). */
export function usdToTokens(usd: number, tokenUsdPrice: number): number {
  if (!tokenUsdPrice || tokenUsdPrice <= 0) return 0
  return usd / tokenUsdPrice
}

/** Marketing reference prices (per finished asset) — shown in UI, not charged. */
export const ASSET_PRICES: Record<string, number> = {
  '2D sprite + 8-frame animation': 10,
  'Tileset (16 tiles)': 25,
  'Parallax background (3 layers)': 20,
  'Full 2D character (all anims)': 60,
  '3D model + rig + animations': 100,
}
